import { HookCard } from './store'

// ============================================================
// BANCO DE GANCHOS BRÄVE
// Seed data inspirado en los 15 ejemplos del brief + variaciones
// ============================================================

export const HOOKS_SEED: HookCard[] = [
  {
    id: 'hook-001',
    titulo: '5 cortes de pelo que van a ser tendencia este año',
    categoria: 'Tendencias',
    tipo: 'Tendencia',
    objetivo: 'visibilidad',
    servicio: 'Cortes',
    impacto: 'Alto',
    explicacion: 'Apela al FOMO (miedo a quedarse fuera) y posiciona la estilista como referente de tendencias.',
    dolor: 'Miedo a quedarse desactualizada o parecer anticuada.',
    deseo: 'Pertenecer al grupo de mujeres que llevan lo último.',
    ideaVisual: 'Collage rápido de 5 cortes en tendencia con transiciones al ritmo de la música.',
  },
  {
    id: 'hook-002',
    titulo: 'El error que hace que tu color pierda brillo antes de tiempo',
    categoria: 'Errores comunes',
    tipo: 'Dolor',
    objetivo: 'autoridad',
    servicio: 'Cuidado en casa',
    impacto: 'Alto',
    explicacion: 'Toca un dolor universal (color que se apaga) y promete revelar la causa. Genera autoridad inmediata.',
    dolor: 'Ver cómo el color que tanto costó se apaga en dos semanas.',
    deseo: 'Mantener el color vibrante más tiempo sin esfuerzo extra.',
    ideaVisual: 'Primer plano de un cabello apagado vs. cabello brillante, split screen.',
  },
  {
    id: 'hook-003',
    titulo: 'Si tu balayage se ve naranja, puede que estés haciendo esto',
    categoria: 'Balayage',
    tipo: 'Objeción',
    objetivo: 'autoridad',
    servicio: 'Balayage',
    impacto: 'Alto',
    explicacion: 'Nombre un problema específico muy común en balayage. La clienta se siente identificada al instante.',
    dolor: 'Tener un balayage que se ve naranja o cobrizo y no saber por qué.',
    deseo: 'Un balayage limpio, frío y luminoso como en Pinterest.',
    ideaVisual: 'Foto de un balayage cobrizo vs. un balayaje correcto, comparativa lado a lado.',
  },
  {
    id: 'hook-004',
    titulo: 'No todos los rubios favorecen igual',
    categoria: 'Rubios',
    tipo: 'Educativo',
    objetivo: 'autoridad',
    servicio: 'Rubios',
    impacto: 'Alto',
    explicacion: 'Revela una verdad que muchas clientas ignoran. Genera curiosidad sobre cuál es SU rubio.',
    dolor: 'Haberse teñido de rubio y sentir que no le favorece.',
    deseo: 'Encontrar el rubio que sí le sienta bien a su tono de piel.',
    ideaVisual: 'Mosaico de 4 rubios diferentes sobre pieles distintas, marcando cuál queda mejor en cada una.',
  },
  {
    id: 'hook-005',
    titulo: '3 señales de que tu cabello necesita un tratamiento',
    categoria: 'Tratamientos',
    tipo: 'Educativo',
    objetivo: 'reservas',
    servicio: 'Tratamientos',
    impacto: 'Medio',
    explicacion: 'Lista accionable que invita a la autoevaluación. Conduce naturalmente a reservar.',
    dolor: 'No saber si el cabello está pidiendo ayuda o solo está cansado.',
    deseo: 'Tener un criterio claro para decidir cuándo tratarlo.',
    ideaVisual: 'Tres planos cortos: puntas abiertas, frizz, cabello apagado. Uno por señal.',
  },
  {
    id: 'hook-006',
    titulo: 'El error que cometes antes de hacerte un cambio de look',
    categoria: 'Errores comunes',
    tipo: 'Dolor',
    objetivo: 'autoridad',
    servicio: 'Cortes',
    impacto: 'Alto',
    explicacion: 'Curiosidad pura. Promete evitar un arrepentimiento. Funciona muy bien en reels.',
    dolor: 'Haberse arrepentido de un cambio de look en el pasado.',
    deseo: 'Hacer el cambio correcto sin equivocarse.',
    ideaVisual: 'Selfie tuya mirando a cámara con texto encima, transición a un antes/después.',
  },
  {
    id: 'hook-007',
    titulo: 'Lo que nadie te cuenta antes de hacerte un alisado',
    categoria: 'Alisados',
    tipo: 'Objeción',
    objetivo: 'autoridad',
    servicio: 'Alisados',
    impacto: 'Alto',
    explicacion: 'Toca el miedo a lo desconocido. Posiciona a la estilista como honesta y transparente.',
    dolor: 'Miedo a que el alisado dañe el cabello o no salga como espera.',
    deseo: 'Hacerse un alisado sintiéndose informada y segura.',
    ideaVisual: 'Plano de ti trabajando con productos, con texto encima "lo que nadie te cuenta".',
  },
  {
    id: 'hook-008',
    titulo: 'Si tienes canas, esto te interesa',
    categoria: 'Canas',
    tipo: 'Engagement',
    objetivo: 'visibilidad',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Filtro directo a un nicho. Aumenta el tiempo de visualización de las personas identificadas.',
    dolor: 'Sentir que las canas envejecen y no saber qué hacer.',
    deseo: 'Cubrir, integrar o lucir las canas con elegancia.',
    ideaVisual: 'Antes/después de un coverage de canas o un gray blending sutil.',
  },
  {
    id: 'hook-009',
    titulo: 'La diferencia entre un rubio bonito y un rubio bien hecho',
    categoria: 'Rubios',
    tipo: 'Autoridad',
    objetivo: 'autoridad',
    servicio: 'Rubios',
    impacto: 'Alto',
    explicacion: 'Diferencia sutil que solo una experta puede explicar. Refuerza autoridad técnica.',
    dolor: 'Haber pagado un rubio que se ve "bonito" pero no profesional.',
    deseo: 'Lucir un rubio que se note bien hecho, que dure y no se rompa.',
    ideaVisual: 'Comparativa de dos rubios: uno con bandas, otro con degradado limpio.',
  },
  {
    id: 'hook-010',
    titulo: 'Por qué tu color no se ve como el de la foto',
    categoria: 'Color',
    tipo: 'Objeción',
    objetivo: 'autoridad',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Aborda la objeción más común del sector. Educa y previene frustraciones futuras.',
    dolor: 'Llevar una foto de Pinterest y que el resultado no se parezca en nada.',
    deseo: 'Entender qué se puede y qué no se puede lograr con su cabello.',
    ideaVisual: 'Pantalla dividida: la foto de referencia vs. el resultado real explicando las diferencias.',
  },
  {
    id: 'hook-011',
    titulo: '3 cosas que revisamos antes de hacer un balayage',
    categoria: 'Balayage',
    tipo: 'Autoridad',
    objetivo: 'autoridad',
    servicio: 'Balayage',
    impacto: 'Medio',
    explicacion: 'Muestra el proceso profesional detrás del servicio. Genera confianza y justifica el precio.',
    dolor: 'Dudas sobre si la estilista sabe lo que hace o solo aplica sin más.',
    deseo: 'Sentirse en manos de una profesional que analiza antes de actuar.',
    ideaVisual: 'Plano de tus manos revisando el cabello de la clienta, evaluando grosor, color base, etc.',
  },
  {
    id: 'hook-012',
    titulo: 'No necesitas cambiar todo tu cabello para verte diferente',
    categoria: 'Balayage',
    tipo: 'Deseo',
    objetivo: 'reservas',
    servicio: 'Balayage',
    impacto: 'Alto',
    explicacion: 'Quita el miedo al cambio drástico. Baja la barrera de entrada para clientas indecisas.',
    dolor: 'Miedo a un cambio radical que no pueda deshacer.',
    deseo: 'Un cambio visible pero sutil que la haga sentir renovada.',
    ideaVisual: 'Antes/después de un iluminados sutil o un babylights discreto.',
  },
  {
    id: 'hook-013',
    titulo: 'Este es el motivo por el que tu melena se ve apagada',
    categoria: 'Tratamientos',
    tipo: 'Dolor',
    objetivo: 'reservas',
    servicio: 'Tratamientos',
    impacto: 'Medio',
    explicacion: 'Diagnóstico que invita a reservar un tratamiento. Sensación de problema resuelto.',
    dolor: 'Tener el pelo apagado y no saber por qué, sintiendo que nada le funciona.',
    deseo: 'Recuperar la luz y el brillo natural del cabello.',
    ideaVisual: 'Cabello apagado al inicio, cabello brillante después de un gloss o baño de color.',
  },
  {
    id: 'hook-014',
    titulo: 'Antes de pedir este color, mira esto',
    categoria: 'Color',
    tipo: 'Objeción',
    objetivo: 'autoridad',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Anticipa una objeción y posiciona a la estilista como honesta. Genera confianza.',
    dolor: 'Haberse decepcionado al pedir un color que no le favorecía.',
    deseo: 'Pedir el color correcto con criterio, no por moda.',
    ideaVisual: 'Tu cara a cámara sosteniendo una mecha, con texto encima "antes de pedir esto".',
  },
  {
    id: 'hook-015',
    titulo: 'La pregunta que siempre hago antes de un cambio de look',
    categoria: 'Autoridad',
    tipo: 'Autoridad',
    objetivo: 'autoridad',
    servicio: 'Cortes',
    impacto: 'Alto',
    explicacion: 'Muestra criterio profesional. Crea curiosidad sobre cuál es la pregunta y por qué importa.',
    dolor: 'Haber cambiado sin pensar y arrepentirse después.',
    deseo: 'Sentir que la estilista cuida el resultado tanto como la clienta.',
    ideaVisual: 'Plano tuyo conversando con la clienta en la silla, primeros segundos de la consulta.',
  },
  {
    id: 'hook-016',
    titulo: 'El mito de que el alisado arruina el cabello',
    categoria: 'Mitos',
    tipo: 'Educativo',
    objetivo: 'autoridad',
    servicio: 'Alisados',
    impacto: 'Alto',
    explicacion: 'Desmiente un mito extendido. Educacional, genera autoridad y abre conversación.',
    dolor: 'Miedo fundado a dañar el cabello con un alisado.',
    deseo: 'Disfrutar de un alisado seguro sin sentir culpa ni riesgo.',
    ideaVisual: 'Cabello antes del alisado (con frizz) vs. después (liso y sano).',
  },
  {
    id: 'hook-017',
    titulo: 'Por qué tu morena iluminada se ve amarilla',
    categoria: 'Color',
    tipo: 'Dolor',
    objetivo: 'autoridad',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Problema muy específico que sufren muchas clientas morenas. Genera identificación inmediata.',
    dolor: 'Pagar una iluminación y ver que se vuelve amarilla en semanas.',
    deseo: 'Una morena iluminada con destinos fríos y elegantes.',
    ideaVisual: 'Comparativa de una morena iluminada amarillenta vs. una bien matizada.',
  },
  {
    id: 'hook-018',
    titulo: 'Lo que cuesta mantener un rubio (y cómo ahorrar en ello)',
    categoria: 'Rubios',
    tipo: 'Venta',
    objetivo: 'reservas',
    servicio: 'Rubios',
    impacto: 'Medio',
    explicacion: 'Honestidad sobre costes. Genera confianza y conduce a un servicio recurrente (mantenimiento).',
    dolor: 'No calcular bien el coste de mantener un rubio y frustrarse.',
    deseo: 'Tener un plan claro de mantenimiento que encaje en su presupuesto.',
    ideaVisual: 'Plano de ti con un calendario de retoque, marcando fechas y costes.',
  },
  {
    id: 'hook-019',
    titulo: 'Antes y después: de cabello dañado a melena sana',
    categoria: 'Antes y después',
    tipo: 'Venta',
    objetivo: 'reservas',
    servicio: 'Tratamientos',
    impacto: 'Alto',
    explicacion: 'El clásico antes/después nunca falla cuando es real. Conduce directamente a la reserva.',
    dolor: 'Sentir el pelo roto, frágil, sin vida.',
    deseo: 'Recuperar una melena sana que pueda crecer sin romperse.',
    ideaVisual: 'Antes/después en vídeo con movimiento del cabello al final.',
  },
  {
    id: 'hook-020',
    titulo: '3 cosas que debes hacer en casa después de un balayage',
    categoria: 'Cuidado en casa',
    tipo: 'Educativo',
    objetivo: 'autoridad',
    servicio: 'Cuidado en casa',
    impacto: 'Medio',
    explicacion: 'Contenido de valor que cuida a la clienta post-servicio. Refuerza relación y autoridad.',
    dolor: 'Haberse hecho un balayage caro y ver cómo se estropea por no cuidarlo.',
    deseo: 'Saber exactamente qué hacer en casa para que dure.',
    ideaVisual: 'Tres productos concretos en pantalla, con texto de cómo y cuándo usarlos.',
  },
  {
    id: 'hook-021',
    titulo: 'Cortes que rejuvenecen (sin parecer que lo buscas)',
    categoria: 'Cortes',
    tipo: 'Deseo',
    objetivo: 'visibilidad',
    servicio: 'Cortes',
    impacto: 'Alto',
    explicacion: 'Toca un deseo universal sutilmente. Compartible por un amplio público.',
    dolor: 'Sentir que el corte actual la envejece sin saber por qué.',
    deseo: 'Un corte que la fluya y le siente bien sin llamar la atención.',
    ideaVisual: 'Tres cortes concretos sobre tres clientas distintas, marcando el efecto rejuvenecedor.',
  },
  {
    id: 'hook-022',
    titulo: 'Por qué las clientas vuelven cada 4 meses',
    categoria: 'Ventas',
    tipo: 'Venta',
    objetivo: 'reservas',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Prueba social implícita. Refuerza la idea de mantenimiento y fideliza.',
    dolor: 'Sentir que el color se desluce y no saber cuándo volver.',
    deseo: 'Un color siempre perfecto, sin tener que pensar cuándo tocarlo.',
    ideaVisual: 'Tu agenda con citas marcadas, plano de clientas felices saliendo del salón.',
  },
  {
    id: 'hook-023',
    titulo: 'El secreto del brillo que ves en las melenas de Pinterest',
    categoria: 'Tendencias',
    tipo: 'Deseo',
    objetivo: 'visibilidad',
    servicio: 'Tratamientos',
    impacto: 'Alto',
    explicacion: 'Conecta un deseo visual muy potente con un servicio real. Apela a la aspiración.',
    dolor: 'No entender por qué su cabello no brilla como el de las fotos.',
    deseo: 'Tener esa melena brillante y sana que ve en redes.',
    ideaVisual: 'Cabello con movimiento y brillo bajo luz natural, primer plano.',
  },
  {
    id: 'hook-024',
    titulo: 'Cortes para pelo fino que dan volumen real',
    categoria: 'Cortes',
    tipo: 'Deseo',
    objetivo: 'reservas',
    servicio: 'Cortes',
    impacto: 'Alto',
    explicacion: 'Nicho específico con dolor muy concreto. Genera conversión directa.',
    dolor: 'Tener pelo fino y verlo plano, sin volumen, todo el día.',
    deseo: 'Un corte que disimule el poco volumen y la haga sentir con pelo.',
    ideaVisual: 'Antes/después de un corte para pelo fino, marcando el volumen ganado.',
  },
  {
    id: 'hook-025',
    titulo: 'El error que cometen las clientas al lavar el cabello teñido',
    categoria: 'Errores comunes',
    tipo: 'Dolor',
    objetivo: 'autoridad',
    servicio: 'Cuidado en casa',
    impacto: 'Medio',
    explicacion: 'Error cotidiano muy común. Genera autoridad y abre conversación sobre rutina en casa.',
    dolor: 'Ver cómo el color pierde intensidad tras cada lavado.',
    deseo: 'Lavar el cabello sin perder el color recién hecho.',
    ideaVisual: 'Plano tuyo explicando con una toalla o un cepillo, mostrando el error y la alternativa.',
  },
  {
    id: 'hook-026',
    titulo: 'Mito: si tienes canas no puedes ser rubia',
    categoria: 'Mitos',
    tipo: 'Educativo',
    objetivo: 'autoridad',
    servicio: 'Canas',
    impacto: 'Alto',
    explicacion: 'Desmiente una creencia que frena a muchas clientas. Genera interés y posiciona.',
    dolor: 'Renunciar a ser rubia por pensar que con canas no se puede.',
    deseo: 'Poder ser rubia aunque tenga canas, sin que se note el retoque.',
    ideaVisual: 'Clienta con canas, transformación a un rubio bien cubierto y luminoso.',
  },
  {
    id: 'hook-027',
    titulo: 'Carrusel: 5 mitos sobre el alisado que te están frenando',
    categoria: 'Mitos',
    tipo: 'Educativo',
    objetivo: 'autoridad',
    servicio: 'Alisados',
    impacto: 'Medio',
    explicacion: 'Formato carrusel pensado para guardar y compartir. Excelente para alcance y autoridad.',
    dolor: 'Quererse alisar pero tener miedo por mitos que ha oído.',
    deseo: 'Tomar la decisión con información real y clara.',
    ideaVisual: 'Carrusel de 5 slides con un mito por slide y la verdad al lado.',
  },
  {
    id: 'hook-028',
    titulo: 'Cuento contigo: 3 plazas esta semana para balayage',
    categoria: 'Ventas',
    tipo: 'Venta',
    objetivo: 'reservas',
    servicio: 'Balayage',
    impacto: 'Alto',
    explicacion: 'Urgencia real y exclusividad. Conduce a reserva inmediata por miedo a perder el sitio.',
    dolor: 'Llevar tiempo queriendo un balayage y no decidirse.',
    deseo: 'Reservar ahora y sentir que ha conseguido una plaza codiciada.',
    ideaVisual: 'Tu cara a cámara, en el salón, con la agenda en mano mostrando los huecos.',
  },
  {
    id: 'hook-029',
    titulo: 'Lo que noté en esta clienta antes de tocar su cabello',
    categoria: 'Autoridad',
    tipo: 'Autoridad',
    objetivo: 'autoridad',
    servicio: 'Color',
    impacto: 'Alto',
    explicacion: 'Muestra análisis profesional previo. Posiciona como alguien que mira antes de actuar.',
    dolor: 'Sentir que en otros salones no la miran antes de aplicar producto.',
    deseo: 'Sentirse observada, escuchada y analizada antes del cambio.',
    ideaVisual: 'Plano tuyo evaluando el cabello de la clienta, tocando mechas, mirando al detalle.',
  },
  {
    id: 'hook-030',
    titulo: 'Si tu cabello se rompe, lee esto antes de pedir una keratina',
    categoria: 'Tratamientos',
    tipo: 'Objeción',
    objetivo: 'autoridad',
    servicio: 'Keratina',
    impacto: 'Alto',
    explicacion: 'Anticipa una objeción técnica. Refuerza autoridad y genera confianza.',
    dolor: 'Tener el pelo roto y no saber si la keratina ayudará o empeorará.',
    deseo: 'Tomar la decisión correcta para su cabello dañado.',
    ideaVisual: 'Plano de puntas rotas, transición a un cabello tratado y sano.',
  },
]

// Categorías disponibles en los filtros
export const HOOK_CATEGORIAS = [
  'Balayage',
  'Rubios',
  'Color',
  'Tratamientos',
  'Alisados',
  'Cortes',
  'Canas',
  'Cuidado en casa',
  'Errores comunes',
  'Tendencias',
  'Mitos',
  'Antes y después',
  'Autoridad',
  'Ventas',
  'Stories',
  'Reels virales',
]

export const HOOK_TIPOS = [
  'Viral',
  'Educativo',
  'Autoridad',
  'Venta',
  'Engagement',
  'Dolor',
  'Deseo',
  'Objeción',
  'Tendencia',
] as const
